services:
  client:
    image: microservices-client:v1
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client
    ports:
      - 3000:3000

  comments:
    image: microservices-comments:v1
    build:
      context: ./comments
      dockerfile: Dockerfile
    container_name: comments
    ports:
      - 4001:4001

  event-bus:
    image: microservices-event-bus:v1
    build:
      context: ./event-bus
      dockerfile: Dockerfile
    container_name: event-bus
    ports:
      - 4005:4005

  moderation:
    image: microservices-moderation:v1
    build:
      context: ./moderation
      dockerfile: Dockerfile
    container_name: moderation
    ports:
      - 4003:4003

  posts:
    image: microservices-posts:v1
    build:
      context: ./posts
      dockerfile: Dockerfile
    container_name: posts
    ports:
      - 4000:4000

  query:
    image: microservices-query:v1
    build:
      context: ./query
      dockerfile: Dockerfile
    container_name: query
    ports:
      - 4002:4002
